"""add_fotos_and_historico_id_unique

Revision ID: 1a554f4646ca
Revises: e5f6a7b8c9d0
Create Date: 2026-05-02 22:26:14.061701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a554f4646ca'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamentos', sa.Column('fotos', sa.JSON(), nullable=False, server_default='[]'))
    
    # Limpar duplicados antes de criar a constraint
    op.execute("""
        DELETE FROM historico_calibracoes_padrao a
        USING (
            SELECT id, 
                   row_number() OVER (PARTITION BY padrao_id, numero_certificado ORDER BY data_calibracao DESC, id DESC) as rn
            FROM historico_calibracoes_padrao
        ) b
        WHERE a.id = b.id AND b.rn > 1
    """)
    
    op.drop_constraint(op.f('faixas_medicao_equipamento_id_fkey'), 'faixas_medicao', type_='foreignkey')
    op.create_foreign_key(None, 'faixas_medicao', 'equipamentos', ['equipamento_id'], ['id'])
    op.create_unique_constraint('uq_historico_padrao_certificado', 'historico_calibracoes_padrao', ['padrao_id', 'numero_certificado'])
    op.drop_constraint(op.f('unidades_medida_grandeza_id_fkey'), 'unidades_medida', type_='foreignkey')
    op.create_foreign_key(None, 'unidades_medida', 'grandezas', ['grandeza_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidades_medida', type_='foreignkey')
    op.create_foreign_key(op.f('unidades_medida_grandeza_id_fkey'), 'unidades_medida', 'grandezas', ['grandeza_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_historico_padrao_certificado', 'historico_calibracoes_padrao', type_='unique')
    op.drop_constraint(None, 'faixas_medicao', type_='foreignkey')
    op.create_foreign_key(op.f('faixas_medicao_equipamento_id_fkey'), 'faixas_medicao', 'equipamentos', ['equipamento_id'], ['id'], ondelete='CASCADE')
    op.drop_column('equipamentos', 'fotos')
    # ### end Alembic commands ###
