"""add tag column to equipamentos

Revision ID: 20712668b513
Revises: 1a554f4646ca
Create Date: 2026-05-03 01:00:52.313506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20712668b513'
down_revision: Union[str, Sequence[str], None] = '1a554f4646ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamentos', sa.Column('tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamentos', 'tag')
    # ### end Alembic commands ###
