"""add_quantidade_pontos_default_to_templates

Revision ID: 25850335528e
Revises: 3b7c9d1e2f4a
Create Date: 2026-05-03 21:02:57.931868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25850335528e'
down_revision: Union[str, Sequence[str], None] = '3b7c9d1e2f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formularios_medicao_template', sa.Column('quantidade_pontos_default', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formularios_medicao_template', 'quantidade_pontos_default')
    # ### end Alembic commands ###
