"""f2_core_metrologico_domain_models

Revision ID: 37b2f9ba02f8
Revises: bef60d5ac6a0
Create Date: 2026-05-01 14:43:58.399269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37b2f9ba02f8'
down_revision: Union[str, Sequence[str], None] = 'bef60d5ac6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP TYPE IF EXISTS distribuicaoincerteza CASCADE"))
    op.execute(sa.text("DROP TYPE IF EXISTS statusos CASCADE"))
    op.execute(sa.text("DROP TYPE IF EXISTS statusitemos CASCADE"))
    op.execute(sa.text("DROP TYPE IF EXISTS statusservico CASCADE"))
    op.create_table('fabricantes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('grandezas',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('simbolo', sa.String(length=20), nullable=False),
    sa.Column('unidade_si', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_equipamento',
    sa.Column('grandeza_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grandeza_id'], ['grandezas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_tipos_equipamento_grandeza_id'), 'tipos_equipamento', ['grandeza_id'], unique=False)
    op.create_table('tipos_incerteza_b_template',
    sa.Column('grandeza_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('simbolo', sa.String(length=50), nullable=True),
    sa.Column('distribuicao', sa.Enum('NORMAL', 'RETANGULAR', 'TRIANGULAR', name='distribuicaoincerteza'), nullable=False),
    sa.Column('graus_liberdade', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grandeza_id'], ['grandezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_incerteza_b_template_grandeza_id'), 'tipos_incerteza_b_template', ['grandeza_id'], unique=False)
    op.create_table('clientes_laboratorio',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cnpj', name='uq_cliente_tenant_cnpj')
    )
    op.create_index(op.f('ix_clientes_laboratorio_tenant_id'), 'clientes_laboratorio', ['tenant_id'], unique=False)
    op.create_table('modelos_equipamento',
    sa.Column('tipo_equipamento_id', sa.Integer(), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('capacidade_padrao', sa.Float(), nullable=True),
    sa.Column('resolucao_padrao', sa.Float(), nullable=True),
    sa.Column('unidade_padrao', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricantes.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipamento_id'], ['tipos_equipamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_equipamento_id', 'fabricante_id', 'nome', name='uq_modelo_tipo_fabricante_nome')
    )
    op.create_index(op.f('ix_modelos_equipamento_fabricante_id'), 'modelos_equipamento', ['fabricante_id'], unique=False)
    op.create_index(op.f('ix_modelos_equipamento_tipo_equipamento_id'), 'modelos_equipamento', ['tipo_equipamento_id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipamento_id', sa.Integer(), nullable=False),
    sa.Column('modelo_equipamento_id', sa.Integer(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('capacidade', sa.Float(), nullable=True),
    sa.Column('resolucao', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_equipamento_id'], ['modelos_equipamento.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipamento_id'], ['tipos_equipamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_modelo_equipamento_id'), 'equipamentos', ['modelo_equipamento_id'], unique=False)
    op.create_index(op.f('ix_equipamentos_tenant_id'), 'equipamentos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_equipamentos_tipo_equipamento_id'), 'equipamentos', ['tipo_equipamento_id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', 'ENTREGUE', name='statusos'), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_laboratorio.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero', name='uq_os_tenant_numero')
    )
    op.create_index(op.f('ix_ordens_servico_cliente_id'), 'ordens_servico', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_tenant_id'), 'ordens_servico', ['tenant_id'], unique=False)
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_laboratorio.id'], ),
    sa.ForeignKeyConstraint(['id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrumentos_cliente_id'), 'instrumentos', ['cliente_id'], unique=False)
    op.create_table('itens_os',
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade_prevista', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO', 'EM_CALIBRACAO', 'CONCLUIDO', 'CANCELADO', name='statusitemos'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_os_os_id'), 'itens_os', ['os_id'], unique=False)
    op.create_table('padroes_calibracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_certificado', sa.String(length=100), nullable=True),
    sa.Column('data_calibracao', sa.Date(), nullable=True),
    sa.Column('validade_calibracao', sa.Date(), nullable=True),
    sa.Column('laboratorio_calibrador', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos_calibracao',
    sa.Column('item_os_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=True),
    sa.Column('workbook_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusservico'), nullable=False),
    sa.Column('temperatura_ambiente', sa.Float(), nullable=True),
    sa.Column('umidade_relativa', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['item_os_id'], ['itens_os.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_calibracao_instrumento_id'), 'servicos_calibracao', ['instrumento_id'], unique=False)
    op.create_index(op.f('ix_servicos_calibracao_item_os_id'), 'servicos_calibracao', ['item_os_id'], unique=False)
    op.create_table('incertezas_b_fontes',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('padrao_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_u', sa.Float(), nullable=False),
    sa.Column('distribuicao', sa.Enum('NORMAL', 'RETANGULAR', 'TRIANGULAR', name='distribuicaoincerteza'), nullable=False),
    sa.Column('graus_liberdade', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['padrao_id'], ['padroes_calibracao.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_calibracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incertezas_b_fontes_padrao_id'), 'incertezas_b_fontes', ['padrao_id'], unique=False)
    op.create_index(op.f('ix_incertezas_b_fontes_servico_id'), 'incertezas_b_fontes', ['servico_id'], unique=False)
    op.create_table('pontos_calibracao',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('leituras_instrumento', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('leituras_padrao', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('media_instrumento', sa.Float(), nullable=True),
    sa.Column('desvio_padrao_instrumento', sa.Float(), nullable=True),
    sa.Column('media_padrao', sa.Float(), nullable=True),
    sa.Column('desvio_padrao_padrao', sa.Float(), nullable=True),
    sa.Column('erro', sa.Float(), nullable=True),
    sa.Column('correcao', sa.Float(), nullable=True),
    sa.Column('u_tipo_a', sa.Float(), nullable=True),
    sa.Column('u_tipo_a_padrao', sa.Float(), nullable=True),
    sa.Column('u_combinada', sa.Float(), nullable=True),
    sa.Column('u_expandida', sa.Float(), nullable=True),
    sa.Column('fator_k', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_calibracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_calibracao_servico_id'), 'pontos_calibracao', ['servico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pontos_calibracao_servico_id'), table_name='pontos_calibracao')
    op.drop_table('pontos_calibracao')
    op.drop_index(op.f('ix_incertezas_b_fontes_servico_id'), table_name='incertezas_b_fontes')
    op.drop_index(op.f('ix_incertezas_b_fontes_padrao_id'), table_name='incertezas_b_fontes')
    op.drop_table('incertezas_b_fontes')
    op.drop_index(op.f('ix_servicos_calibracao_item_os_id'), table_name='servicos_calibracao')
    op.drop_index(op.f('ix_servicos_calibracao_instrumento_id'), table_name='servicos_calibracao')
    op.drop_table('servicos_calibracao')
    op.drop_table('padroes_calibracao')
    op.drop_index(op.f('ix_itens_os_os_id'), table_name='itens_os')
    op.drop_table('itens_os')
    op.drop_index(op.f('ix_instrumentos_cliente_id'), table_name='instrumentos')
    op.drop_table('instrumentos')
    op.drop_index(op.f('ix_ordens_servico_tenant_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_cliente_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_equipamentos_tipo_equipamento_id'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_tenant_id'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_modelo_equipamento_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_modelos_equipamento_tipo_equipamento_id'), table_name='modelos_equipamento')
    op.drop_index(op.f('ix_modelos_equipamento_fabricante_id'), table_name='modelos_equipamento')
    op.drop_table('modelos_equipamento')
    op.drop_index(op.f('ix_clientes_laboratorio_tenant_id'), table_name='clientes_laboratorio')
    op.drop_table('clientes_laboratorio')
    op.drop_index(op.f('ix_tipos_incerteza_b_template_grandeza_id'), table_name='tipos_incerteza_b_template')
    op.drop_table('tipos_incerteza_b_template')
    op.drop_index(op.f('ix_tipos_equipamento_grandeza_id'), table_name='tipos_equipamento')
    op.drop_table('tipos_equipamento')
    op.drop_table('grandezas')
    op.drop_table('fabricantes')
    sa.Enum(name='distribuicaoincerteza').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statusos').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statusitemos').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statusservico').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
