"""f2_core_metrologico_domain_models

Revision ID: 732c03e2a964
Revises: bef60d5ac6a0
Create Date: 2026-05-01 01:47:41.838326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '732c03e2a964'
down_revision: Union[str, Sequence[str], None] = 'bef60d5ac6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grandezas',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('simbolo', sa.String(length=20), nullable=False),
    sa.Column('unidade_si', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_incerteza_b_template',
    sa.Column('grandeza_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('simbolo', sa.String(length=50), nullable=True),
    sa.Column('distribuicao', sa.Enum('NORMAL', 'RETANGULAR', 'TRIANGULAR', name='distribuicaoincerteza'), nullable=False),
    sa.Column('graus_liberdade', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grandeza_id'], ['grandezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_incerteza_b_template_grandeza_id'), 'tipos_incerteza_b_template', ['grandeza_id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('grandeza_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('capacidade', sa.Float(), nullable=True),
    sa.Column('resolucao', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grandeza_id'], ['grandezas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_serie', name='uq_equipamento_tenant_serie')
    )
    op.create_index(op.f('ix_equipamentos_grandeza_id'), 'equipamentos', ['grandeza_id'], unique=False)
    op.create_index(op.f('ix_equipamentos_tenant_id'), 'equipamentos', ['tenant_id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('cliente_contato', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', 'ENTREGUE', name='statusos'), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero', name='uq_os_tenant_numero')
    )
    op.create_index(op.f('ix_ordens_servico_tenant_id'), 'ordens_servico', ['tenant_id'], unique=False)
    op.create_table('itens_os',
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO', 'EM_CALIBRACAO', 'CONCLUIDO', 'CANCELADO', name='statusitemos'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_os_equipamento_id'), 'itens_os', ['equipamento_id'], unique=False)
    op.create_index(op.f('ix_itens_os_os_id'), 'itens_os', ['os_id'], unique=False)
    op.create_table('servicos_calibracao',
    sa.Column('item_os_id', sa.Integer(), nullable=False),
    sa.Column('workbook_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusservico'), nullable=False),
    sa.Column('temperatura_ambiente', sa.Float(), nullable=True),
    sa.Column('umidade_relativa', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_os_id'], ['itens_os.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_calibracao_item_os_id'), 'servicos_calibracao', ['item_os_id'], unique=True)
    op.create_table('incertezas_b_fontes',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_u', sa.Float(), nullable=False),
    sa.Column('distribuicao', sa.Enum('NORMAL', 'RETANGULAR', 'TRIANGULAR', name='distribuicaoincerteza'), nullable=False),
    sa.Column('graus_liberdade', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_calibracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incertezas_b_fontes_servico_id'), 'incertezas_b_fontes', ['servico_id'], unique=False)
    op.create_table('pontos_calibracao',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('leituras', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('media', sa.Float(), nullable=True),
    sa.Column('desvio_padrao', sa.Float(), nullable=True),
    sa.Column('correcao', sa.Float(), nullable=True),
    sa.Column('u_tipo_a', sa.Float(), nullable=True),
    sa.Column('u_combinada', sa.Float(), nullable=True),
    sa.Column('u_expandida', sa.Float(), nullable=True),
    sa.Column('fator_k', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_calibracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_calibracao_servico_id'), 'pontos_calibracao', ['servico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pontos_calibracao_servico_id'), table_name='pontos_calibracao')
    op.drop_table('pontos_calibracao')
    op.drop_index(op.f('ix_incertezas_b_fontes_servico_id'), table_name='incertezas_b_fontes')
    op.drop_table('incertezas_b_fontes')
    op.drop_index(op.f('ix_servicos_calibracao_item_os_id'), table_name='servicos_calibracao')
    op.drop_table('servicos_calibracao')
    op.drop_index(op.f('ix_itens_os_os_id'), table_name='itens_os')
    op.drop_index(op.f('ix_itens_os_equipamento_id'), table_name='itens_os')
    op.drop_table('itens_os')
    op.drop_index(op.f('ix_ordens_servico_tenant_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_equipamentos_tenant_id'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_grandeza_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_tipos_incerteza_b_template_grandeza_id'), table_name='tipos_incerteza_b_template')
    op.drop_table('tipos_incerteza_b_template')
    op.drop_table('grandezas')
    # ### end Alembic commands ###
