"""add_outbox_events_table

Revision ID: bef60d5ac6a0
Revises: 9f5e4899ba75
Create Date: 2026-04-22 03:13:22.575148

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bef60d5ac6a0"
down_revision: Union[str, Sequence[str], None] = "9f5e4899ba75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
